### ISSUE TITLE
Don't know how to build task 'swagger_ui:dist:update'

### ISSUE THREAD

**Issue by TangMonk** [TinkerDev/grape-swagger-rails#14]
```bash

rake swagger_ui:dist:update --trace
rake aborted!
Don't know how to build task 'swagger_ui:dist:update'
/Users/tangmonk/.rvm/gems/ruby-2.1.5/gems/rake-10.4.2/lib/rake/task_manager.rb:62:in `[]'
/Users/tangmonk/.rvm/gems/ruby-2.1.5/gems/rake-10.4.2/lib/rake/application.rb:149:in `invoke_task'
/Users/tangmonk/.rvm/gems/ruby-2.1.5/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/tangmonk/.rvm/gems/ruby-2.1.5/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/Users/tangmonk/.rvm/gems/ruby-2.1.5/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/Users/tangmonk/.rvm/gems/ruby-2.1.5/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/Users/tangmonk/.rvm/gems/ruby-2.1.5/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/Users/tangmonk/.rvm/gems/ruby-2.1.5/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/Users/tangmonk/.rvm/gems/ruby-2.1.5/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/Users/tangmonk/.rvm/gems/ruby-2.1.5/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
```

**Comment by dblock** [comment]
This is something we run part of this gem, not part of your application. If you want grape-swagger-rails to pickup the latest, form the source, run the rake task, examine the diff, fix any bugs, make sure tests pass and PR it here.

**Comment by calfzhou** [comment]
It would be better to clarify this in README - I just tried several times to update dist before find this issue :grin:
